export const mockUserProfiles = [
  {
    id: '1',
    name: 'Aarav Sharma',
    email: 'aarav@ecolink.in',
    userType: 'individual',
    points: 94,
    itemsDonated: 6,
    itemsRecycled: 4,
    badges: ['first-donation', 'eco-warrior-level-1'],
    joinedDate: '2024-03-15',
    profileImage: '👨',
    avatarInitials: 'AS',
    city: 'Bangalore',
  },
  {
    id: '2',
    name: 'Riya Mehta',
    email: 'riya@ecolink.in',
    userType: 'individual',
    points: 81,
    itemsDonated: 5,
    itemsRecycled: 3,
    badges: ['first-recycle', 'eco-warrior-level-1'],
    joinedDate: '2024-01-10',
    profileImage: '👩',
    avatarInitials: 'RM',
    city: 'Mumbai',
  },
  {
    id: '3',
    name: 'Rahul Verma',
    email: 'rahul@ecolink.in',
    userType: 'individual',
    points: 69,
    itemsDonated: 4,
    itemsRecycled: 3,
    badges: ['first-donation'],
    joinedDate: '2024-02-01',
    profileImage: '🧑',
    avatarInitials: 'RV',
    city: 'Delhi',
  },
  {
    id: '4',
    name: 'Green Campus Foundation',
    email: 'admin@greencampus.in',
    userType: 'institutional',
    points: 320,
    itemsDonated: 25,
    itemsRecycled: 15,
    badges: ['eco-warrior-level-2', 'collector'],
    joinedDate: '2024-01-25',
    profileImage: '🏫',
    avatarInitials: 'GC',
    city: 'Hyderabad',
  },
];

export const mockWasteItems = [
  {
    id: '1',
    category: 'laptop',
    title: 'Old Lenovo Laptop',
    condition: 'not-working',
    description: 'Screen flickers and keyboard has key issues.',
    image: '💻',
    action: 'recycle',
    points: 5,
    createdAt: '2024-05-01',
    status: 'completed',
  },
  {
    id: '2',
    category: 'mobile',
    title: 'Redmi Note 8',
    condition: 'working',
    description: 'Slight scratches but fully functional.',
    image: '📱',
    action: 'donate',
    points: 10,
    createdAt: '2024-04-28',
    status: 'pending-pickup',
  },
  {
    id: '3',
    category: 'battery',
    title: 'Old Laptop Battery',
    condition: 'not-working',
    description: 'Does not hold charge for more than 10 minutes.',
    image: '🔋',
    action: 'recycle',
    points: 5,
    createdAt: '2024-04-20',
    status: 'completed',
  },
];
