export const mockVendors = [
  {
    id: '1',
    name: 'Green Earth Recycling',
    location: 'Bangalore',
    address: '12 MG Road, Bengaluru, Karnataka 560001',
    phone: '+91 98765 43210',
    email: 'contact@greenearth.in',
    rating: 4.8,
    reviews: 342,
    acceptedCategories: ['mobile', 'laptop', 'battery', 'charger', 'keyboard'],
    pickupAvailable: true,
    image: '🏭',
  },
  {
    id: '2',
    name: 'EcoWaste Solutions India',
    location: 'Mumbai',
    address: '45 Andheri Link Road, Mumbai, Maharashtra 400053',
    phone: '+91 99880 11223',
    email: 'hello@ecowasteindia.in',
    rating: 4.6,
    reviews: 218,
    acceptedCategories: ['mobile', 'laptop', 'monitor', 'printer', 'router'],
    pickupAvailable: true,
    image: '🌍',
  },
  {
    id: '3',
    name: 'CleanTech Bangalore',
    location: 'Bangalore',
    address: '88 Whitefield Main Road, Bengaluru, Karnataka 560066',
    phone: '+91 99001 22110',
    email: 'support@cleantechblr.in',
    rating: 4.7,
    reviews: 456,
    acceptedCategories: ['mobile', 'laptop', 'battery', 'headphones', 'all'],
    pickupAvailable: false,
    image: '♻️',
  },
  {
    id: '4',
    name: 'Delhi E-Cycle Foundation',
    location: 'Delhi',
    address: '21 Nehru Place, New Delhi, Delhi 110019',
    phone: '+91 98111 44556',
    email: 'connect@ecyclefoundation.org',
    rating: 4.5,
    reviews: 189,
    acceptedCategories: ['mobile', 'laptop', 'keyboard', 'router'],
    pickupAvailable: true,
    image: '🔧',
  },
  {
    id: '5',
    name: 'Hyderabad Green Loop',
    location: 'Hyderabad',
    address: '77 Banjara Hills Road, Hyderabad, Telangana 500034',
    phone: '+91 97000 77889',
    email: 'care@greenloop.in',
    rating: 4.9,
    reviews: 523,
    acceptedCategories: ['all'],
    pickupAvailable: true,
    image: '🌎',
  },
  {
    id: '6',
    name: 'Chennai ReNew E-Waste',
    location: 'Chennai',
    address: '9 Anna Salai, Chennai, Tamil Nadu 600002',
    phone: '+91 98450 66778',
    email: 'team@renewchennai.in',
    rating: 4.4,
    reviews: 141,
    acceptedCategories: ['mobile', 'battery', 'charger', 'other'],
    pickupAvailable: false,
    image: '🏢',
  },
];

export const mockLeaderboard = [
  {
    id: '1',
    name: 'Aarav Sharma',
    points: 940,
    rank: 1,
    itemsDonated: 14,
    itemsRecycled: 9,
    badge: '🌿',
    avatar: 'AS',
  },
  {
    id: '2',
    name: 'Riya Mehta',
    points: 815,
    rank: 2,
    itemsDonated: 11,
    itemsRecycled: 7,
    badge: '♻️',
    avatar: 'RM',
  },
  {
    id: '3',
    name: 'Rahul Verma',
    points: 690,
    rank: 3,
    itemsDonated: 9,
    itemsRecycled: 6,
    badge: '🌱',
    avatar: 'RV',
  },
  {
    id: '4',
    name: 'Sneha Iyer',
    points: 560,
    rank: 4,
    itemsDonated: 7,
    itemsRecycled: 4,
    badge: '🌱',
    avatar: 'SI',
  },
  {
    id: '5',
    name: 'Ankit Rao',
    points: 498,
    rank: 5,
    itemsDonated: 6,
    itemsRecycled: 3,
    badge: '🎁',
    avatar: 'AR',
  },
  {
    id: '6',
    name: 'Priya Nair',
    points: 452,
    rank: 6,
    itemsDonated: 5,
    itemsRecycled: 4,
    badge: null,
    avatar: 'PN',
  },
  {
    id: '7',
    name: 'Neha Kapoor',
    points: 407,
    rank: 7,
    itemsDonated: 4,
    itemsRecycled: 3,
    badge: null,
    avatar: 'NK',
  },
  {
    id: '8',
    name: 'Vikram Das',
    points: 366,
    rank: 8,
    itemsDonated: 3,
    itemsRecycled: 2,
    badge: null,
    avatar: 'VD',
  },
];

export const mockPickupRequests = [
  {
    id: '1',
    vendorId: '1',
    status: 'pending',
    scheduledDate: '2026-05-10',
    scheduledTime: '10:00 AM - 2:00 PM',
    itemsCount: 2,
    address: '302 Indiranagar, Bengaluru',
  },
  {
    id: '2',
    vendorId: '3',
    status: 'accepted',
    scheduledDate: '2026-05-08',
    scheduledTime: '2:00 PM - 6:00 PM',
    itemsCount: 1,
    address: '14 Jubilee Hills, Hyderabad',
  },
];
